language: ruby

rvm:
  - 2.1.7

sudo: required
dist: trusty
group: deprecated-2017Q4

branches:
  only:
  - master

notifications:
  email:
    recipients:
      - jose.aceves.chamosa@gmail.com
    on_success: always
    on_failure: always 
