language: ruby
sudo: false
rvm:
  - 2.0.0
  - ruby-head
  - jruby-9.1.15.0
  - jruby-head
before_script:
  - unset JRUBY_OPTS
  - unset _JAVA_OPTIONS

notifications:
  email:
    recipients:
      - jose.aceves.chamosa@gmail.com
    on_success: always
    on_failure: always 
